name: switch_game
version: 1.0.0+1
publish_to: none
description: switch 游戏.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  get: 4.6.5
  getwidget: ^3.0.1
  window_manager: ^0.2.8
  dio: ^4.0.6
  html: ^0.15.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.7
  windows_notification: ^0.0.3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/assets/images/

