name: switch_game
version: 1.0.4
publish_to: none
description: switch 游戏.
environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  getwidget: ^4.0.0
  window_manager: ^0.3.9
  dio: ^5.5.0+1
  html: ^0.15.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.7
  windows_notification: ^1.2.0
  webview_windows: ^0.4.0
  get_storage: ^2.0.3
  file_picker: ^8.0.6
  cached_network_image: ^3.2.3
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
    - family: iconfont
      fonts:
        - asset: lib/assets/fonts/iconfont.ttf
